from app.agents.schemas import RoleType

ROLE_PERMISSIONS = {
    "ADMIN": {
        # Patient tools
        "list_patients",
        "get_patient_by_id",
        "get_patient_by_email",
        "get_patients_by_name",
        "create_patient",
        "update_patient",
        # Doctor tools
        "list_doctors",
        "get_doctor_by_id",
        "get_doctor_by_email",
        "get_doctors_by_name",
        "get_doctors_by_specialization",
        "create_doctor",
        "update_doctor",
        # Session tools
        "list_sessions",
        "get_session_by_id",
        "get_sessions_by_doctor",
        "get_sessions_by_date",
        "get_sessions_by_status",
        "get_session_slots",
        "create_session",
        "update_session",
        "cancel_session",
        # Staff tools
        "list_staff",
        "get_staff_by_id",
        "get_staff_by_email",
        "get_staff_by_name",
        "get_staff_by_role",
        "create_staff",
        "update_staff",
        # Appointment tools
        "list_appointments",
        "get_appointment_by_id",
        "get_appointments_by_patient",
        "get_appointments_by_doctor",
        "get_appointments_by_status",
        "get_upcoming_active_appointments",
        "get_active_appointments_today",
        "get_appointments_by_date",
        "suggest_available_slot",
        "create_appointment",
        "update_appointment",
        "cancel_appointment",
        # Waitlist tools
        "list_waitlist",
        "get_waitlist_entry",
        "get_waitlist_by_patient",
        "get_waitlist_by_session",
        "join_waitlist",
        "leave_waitlist",
    },
    "RECEPTIONIST": {
        "list_patients",
        "get_patient_by_id",
        "get_patient_by_email",
        "get_patients_by_name",
        "create_patient",
        "update_patient",
        "list_doctors",
        "get_doctor_by_id",
        "get_doctor_by_email",
        "get_doctors_by_name",
        "get_doctors_by_specialization",
        "create_doctor",
        "update_doctor",
        "list_sessions",
        "get_session_by_id",
        "get_sessions_by_doctor",
        "get_sessions_by_date",
        "get_sessions_by_status",
        "get_session_slots",
        "create_session",
        "update_session",
        "cancel_session",
        "list_appointments",
        "get_appointment_by_id",
        "get_appointments_by_patient",
        "get_appointments_by_doctor",
        "get_appointments_by_status",
        "get_upcoming_active_appointments",
        "get_active_appointments_today",
        "get_appointments_by_date",
        "suggest_available_slot",
        "create_appointment",
        "update_appointment",
        "cancel_appointment",
        "list_waitlist",
        "get_waitlist_entry",
        "get_waitlist_by_patient",
        "get_waitlist_by_session",
        "join_waitlist",
        "leave_waitlist",
    },
    "DOCTOR": {
        "list_doctors",
        "get_doctor_by_id",
        "get_doctor_by_email",
        "get_doctors_by_name",
        "get_doctors_by_specialization",
        "list_patients",
        "get_patient_by_id",
        "get_patient_by_email",
        "get_patients_by_name",
        "list_sessions",
        "get_session_by_id",
        "get_sessions_by_doctor",
        "get_sessions_by_date",
        "get_sessions_by_status",
        "get_session_slots",
        "get_appointment_by_id",
        "get_appointments_by_patient",
        "get_appointments_by_doctor",
        "get_appointments_by_status",
        "get_upcoming_active_appointments",
        "get_active_appointments_today",
        "get_appointments_by_date",
        "list_waitlist",
        "get_waitlist_entry",
        "get_waitlist_by_patient",
        "get_waitlist_by_session",
    },
    "PATIENT": {
        "list_doctors",
        "get_doctor_by_id",
        "get_doctor_by_email",
        "get_doctors_by_name",
        "get_doctors_by_specialization",
        "get_appointment_by_id",
        "get_appointments_by_patient",
        "get_upcoming_active_appointments",
        "get_active_appointments_today",
        "get_appointments_by_date",
        "suggest_available_slot",
        "create_appointment",
        "cancel_appointment",
        "join_waitlist",
        "leave_waitlist",
    },
}


def is_action_allowed(role: RoleType, action_name: str) -> bool:
    return action_name in ROLE_PERMISSIONS.get(role, set())
